POST  http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username":"rajtest56",
    "email":"testgmil@gmail.com",
    "password":"rajtest56"
}

### Login Route
POST  http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"testgmil@gmail.com",
    "password":"stayflow"
}

### GET Profile

GET http://localhost:3000/api/v1/auth/me
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwNDc3MDE0fQ.K4hLzs2l-HjTHOC7zqDhS_WAq71N-rPCQ7XkQgdjAFk; Max-Age=86400; Path=/; Expires=Sat, 07 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwOTk1NDE0fQ.P72Fuoz0LUhXA_0Ghegn0tMaJFFLKJ9EKuKcOMOTecE; Max-Age=604800; Path=/; Expires=Fri, 13 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict


### Logout

POST http://localhost:3000/api/v1/auth/logout
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwNDc3MDE0fQ.K4hLzs2l-HjTHOC7zqDhS_WAq71N-rPCQ7XkQgdjAFk; Max-Age=86400; Path=/; Expires=Sat, 07 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwOTk1NDE0fQ.P72Fuoz0LUhXA_0Ghegn0tMaJFFLKJ9EKuKcOMOTecE; Max-Age=604800; Path=/; Expires=Fri, 13 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict

### Update User
PUT http://localhost:3000/api/v1/user/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwNDc3MDE0fQ.K4hLzs2l-HjTHOC7zqDhS_WAq71N-rPCQ7XkQgdjAFk; Max-Age=86400; Path=/; Expires=Sat, 07 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwOTk1NDE0fQ.P72Fuoz0LUhXA_0Ghegn0tMaJFFLKJ9EKuKcOMOTecE; Max-Age=604800; Path=/; Expires=Fri, 13 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "username": "sukhraj singh"
}

### Forgetting password
POST http://localhost:3000/api/v1/auth/forget-password
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwNDc3MDE0fQ.K4hLzs2l-HjTHOC7zqDhS_WAq71N-rPCQ7XkQgdjAFk; Max-Age=86400; Path=/; Expires=Sat, 07 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwOTk1NDE0fQ.P72Fuoz0LUhXA_0Ghegn0tMaJFFLKJ9EKuKcOMOTecE; Max-Age=604800; Path=/; Expires=Fri, 13 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "oldPassword": "rajtest56",
    "newPassword": "stayflow"
}

### Update user Role By iD
PATCH http://localhost:3000/api/v1/user/cc4b2ac7-adca-4ff4-b3f7-d16d7dbec451/role
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwNDc3MDE0fQ.K4hLzs2l-HjTHOC7zqDhS_WAq71N-rPCQ7XkQgdjAFk; Max-Age=86400; Path=/; Expires=Sat, 07 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDM5MDYxNCwiZXhwIjoxNzcwOTk1NDE0fQ.P72Fuoz0LUhXA_0Ghegn0tMaJFFLKJ9EKuKcOMOTecE; Max-Age=604800; Path=/; Expires=Fri, 13 Feb 2026 15:10:14 GMT; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "id": "cc4b2ac7-adca-4ff4-b3f7-d16d7dbec451",
    "role": "admin"
}

### Delete User
DELETE  http://localhost:3000/api/v1/auth/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NTQ5ODU2LWFkZGYtNDcxYy04OGU2LTQxMDVjM2ExZTcyMSIsImlhdCI6MTc3MDIxOTQ2OSwiZXhwIjoxNzcwMzA1ODY5fQ.ZAHMTxvRQogEOo-kjFvYSMXKhPsgSttYQvKjzdkhLvo; Max-Age=86400; Path=/; Expires=Thu, 05 Feb 2026 15:37:49 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1NTQ5ODU2LWFkZGYtNDcxYy04OGU2LTQxMDVjM2ExZTcyMSIsImlhdCI6MTc3MDIxOTQ2OSwiZXhwIjoxNzcwODI0MjY5fQ.Hgfq0cV29mNR4tme2RjUlC7Deydolkwzv3bnQiLk2qs; Max-Age=604800; Path=/; Expires=Wed, 11 Feb 2026 15:37:49 GMT; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "id": "c5549856-addf-471c-88e6-4105c3a1e721"
}

### Update Status ById
PATCH http://localhost:3000/api/v1/user/cc4b2ac7-adca-4ff4-b3f7-d16d7dbec451/status
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDQ3NDkwNywiZXhwIjoxNzcwNTYxMzA3fQ.rn5DWOyhHXiFVs0mAdNVvkwS4-xDhtBP3gArafx5oms; Max-Age=86400; Path=/; Expires=Sun, 08 Feb 2026 14:35:07 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDQ3NDkwNywiZXhwIjoxNzcxMDc5NzA3fQ.PiZhcKoM0nGhrO1BfYAvpzts8pG15KfOJqjWxV9jOyM; Max-Age=604800; Path=/; Expires=Sat, 14 Feb 2026 14:35:07 GMT; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "status": "Active"
}

### Create Room 
POST http://localhost:3000/api/v1/hotel/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDY1MDU0MiwiZXhwIjoxNzcwNzM2OTQyfQ.duYFx_XHQ-LYA3u-LRupe23NQaEoWU2sGtRssDxFrGsEzpvRzi; Max-Age=86400; Path=/; Expires=Tue, 10 Feb 2026 15:22:22 GMT; HttpOnly; SameSite=Strict,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNjNGIyYWM3LWFkY2EtNGZmNC1iM2Y3LWQxNmQ3ZGJlYzQ1MSIsImlhdCI6MTc3MDY1MDU0MiwiZXhwIjoxNzcxMjU1MzQyfQ.GWTFFdRmyFYa9Q2Ny3Qxg4MmQc7221xCncOHlPhfI28; Max-Age=604800; Path=/; Expires=Mon, 16 Feb 2026 15:22:22 GMT; HttpOnly; SameSite=Strict
Content-Type: application/json

{
    "name": "Relvence Hotel",
    "location": "Delhi,1245",
    "city": "Delhi",
    "contactEmail": "sukhrajgamer0@gmail.com",
    "contactPhone": "+91 111111111"
}

### Test Room Photo Upload
PATCH http://localhost:3000/api/v1/hotel/cmlfbqir70000l4780gd4h5g8/image
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="hotelIMG"; filename="example.png"
Content-Type: image/png

< ./example.png
------MyBoundary--